kind: PersistentVolume
apiVersion: v1
metadata:
  name: account-microservice-postgresql
  labels:
    type: local
    app: account-microservice-postgresql
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/account-microservice"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: account-microservice-postgresql
  labels:
    app: account-microservice-postgresql
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi