apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-accountmicroservice-deployment
  labels:
    app: postgresql-accountmicroservice
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql-accountmicroservice
  template:
    metadata:
      labels:
        app: postgresql-accountmicroservice
    spec:
      containers:
        - name: postgresql-accountmicroservice
          image: postgres:14.2
          ports:
            - containerPort: 5432
          env:
            - name: "POSTGRES_USER"
              value: "Sina"
            - name: "POSTGRES_PASSWORD"
              valueFrom:
                secretKeyRef:
                  name: postgresql-accountmicroservice-credentials
                  key: password
                  optional: false
            - name: "POSTGRES_DB"
              value: "beavergoose"
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgresql-accountmicroservice-db
      volumes:
        - name: postgresql-accountmicroservice-db
          persistentVolumeClaim:
            claimName: postgresql-accountmicroservice-pv-claim