# config.yaml
ingress:
  annotations:
    kubernetes.io/ingress.class: nginx

image:
  repository: datalust/seq
  tag: 2022.1
  pullPolicy: Always

acceptEULA: "Y"

ui:
  service:
    port: 80
  ingress:
    enabled: true
    path: /
    hosts:
      - sequi.demo-beavergoose.nl

ingestion:
  service:
    port: 5341
  ingress:
    enabled: true
    path: /
    hosts:
      - seqingestion.demo-beavergoose.nl

resources:
  requests:
    memory: 512Mi
  limits:
    memory: 2Gi

persistence:
  enabled: true

  existingClaim: seqdata-pv-claim
  accessMode: ReadWriteOnce
  size: 3Gi