kind: PersistentVolume
apiVersion: v1
metadata:
  name: seqdata
  labels:
    type: local
    app: seq
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/seqdata"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seqdata
  labels:
    app: seq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 2Gi