kind: PersistentVolume
apiVersion: v1
metadata:
  name: seqdata-pv
  labels:
    type: local
    app: seq
spec:
  storageClassName: manual
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 3Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt/data/seq"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: seqdata-pv-claim
  labels:
    app: seq
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 3Gi