apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.name }}
  labels:
    app: {{ .Values.name }}
spec:
  selector:
    matchLabels:
      app: {{ .Values.name }}
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: {{ .Values.name }}
    spec:
      containers:
        - name: {{ .Values.name }}
          image: {{ .Values.deploy.image }}:{{ .Values.deploy.tag }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.deploy.containerPort }}
          env:
          {{ range $v := .Values.deploy.envConfigMap }}
            - name: {{ $v | quote }}
              valueFrom:
                configMapKeyRef:
                {{ range $q, $w := .Values.deploy.configMaps }}
                  name: $q
                  key: $w
                {{- end }}
          {{- end }}
          {{ range $z := .Values.deploy.envSecret }}
            - name: {{ $z | quote }}
              valueFrom:
                secretKeyRef:
                {{ range $a, $b := .Values.deploy.secrets }}
                  name: $a
                  key: $b
                  optional: false
                {{- end }}
          {{- end }}
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "320Mi"
              cpu: "256m"