apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.name }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.name }}
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: {{ .Values.hpa.targetCPUUtilization }}