apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: link-microservice-read-jobs
rules:
  - apiGroups: ["batch","extensions"]
    resources: ["jobs"]
    verbs: ["get","watch","list"]