version: '3.8'

services:
  postgresqlbeavergoose-accountdb:
    image: postgres:14.2
    container_name: postgresqlbeavergoose-accountdb
    environment:
      - POSTGRES_USER=Sina
      - POSTGRES_PASSWORD=sU4m1!rc&1HiNWZZNbB9j!
      - POSTGRES_DB=beavergoose
    ports:
      - "1111:5432"
    volumes:
      - postgresqlbeavergoose-accountdata:/var/lib/postgresql/data
volumes:
  postgresqlbeavergoose-accountdata: