name: "filemicroservice - build, test & analyse"
on:
  push:
    branches:
      - "main"
      - "development"
      - "feature-**"
    paths:
      - "src/Services/FileMicroservice/**"
      - "tests/FileMicroservice/FileMicroservice.UnitTests/**"
      - "tests/FileMicroservice/FileMicroservice.IntegrationTests/**"
      - ".github/workflows/file-microservice-test.yml"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "src/Services/FileMicroservice/**"
      - "tests/FileMicroservice/FileMicroservice.UnitTests/**"
      - "tests/FileMicroservice/FileMicroservice.IntegrationTests/**"
      - ".github/workflows/file-microservice-test.yml"

jobs:
  file-build-unit-testing:
    uses: "./.github/workflows/template-build-test.yml"
    with:
      project-location: "src/Services/FileMicroservice"
      test-location: "tests/FileMicroservice/FileMicroservice.UnitTests"
      project-name: "FileMicroservice"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  file-integration-testing:
    uses: "./.github/workflows/template-integration-test.yml"
    with:
      test-location: "tests/FileMicroservice/FileMicroservice.IntegrationTests"
      project-name: "FileMicroservice"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  file-analyse:
    uses: "./.github/workflows/template-analyse.yml"
    with:
      project-location: "src/Services/FileMicroservice"
      test-location: "tests/FileMicroservice/FileMicroservice.UnitTests"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}