name: "linkmicroservice - deploy"
on:
  push:
    branches:
      - "release-**"

jobs:
  link-docker-dockerhub:
    uses: "./.github/workflows/workflow-deploy-dockerhub.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      project-name: "linkmicroservice"
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
  link-docker-dockerhub-dbmigration:
    uses: "./.github/workflows/workflow-deploy-dockerhub.yml"
    needs: link-docker-dockerhub
    with:
      project-location: "deploy/databases/LinkMicroservice.DBMigration"
      project-name: "linkmicroservice-dbmigration"
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
  link-kubernetes-job-dbmigration:
    uses: "./.github/workflows/workflow-deploy-kubernetes-job.yml"
    needs: link-docker-dockerhub-dbmigration
    with:
      project-name: "linkmicroservice"
    secrets:
      digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      digitalocean-cluster-name: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
  link-kubernetes-deployment:
    uses: "./.github/workflows/workflow-deploy-kubernetes.yml"
    needs: link-kubernetes-job-dbmigration
    with:
      project-name: "linkmicroservice"
    secrets:
      digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      digitalocean-cluster-name: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}