name: "linkmicroservice - deploy"
on:
  push:
    branches:
      - "release-**"

jobs:
  link-docker:
    uses: "./.github/workflows/template-deploy-dockerhub.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      project-name: "linkmicroservice"
      version: ${ GITHUB_REF_NAME }
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
  link-dbmigration-docker:
    uses: "./.github/workflows/template-deploy-dockerhub.yml"
    needs: link-docker
    with:
      project-location: "deploy/databases/LinkMicroservice.DBMigration"
      project-name: "linkmicroservice-dbmigration"
      version: ${ GITHUB_REF_NAME }
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
  link-dbmigration-job-kubernetes:
    uses: "./.github/workflows/template-dbmigration-job-kubernetes.yml"
    needs: link-dbmigration-job-kubernetes
    with:
      project-location: "deploy/databases/LinkMicroservice.DBMigration"
      project-name: "linkmicroservice"
      version: ${ GITHUB_REF_NAME }
    secrets:
      digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      digitalocean-cluster-name: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}
  link-deployment-kubernetes:
    uses: "./.github/workflows/template-deploy-kubernetes.yml"
    needs: link-dbmigration-job-kubernetes
    with:
      project-location: "src/Services/LinkMicroservice"
      project-name: "linkmicroservice"
      version: ${ GITHUB_REF_NAME }
    secrets:
      digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      digitalocean-cluster-name: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}