name: "linkmicroservice - build, test & analyse"
on:
  push:
    branches:
      - "main"
      - "development"
      - "feature-**"
      - "techdebt-**"
    paths:
      - "src/Services/LinkMicroservice/**"
      - "tests/LinkMicroservice/LinkMicroservice.UnitTests/**"
      - "tests/LinkMicroservice/LinkMicroservice.IntegrationTests/**"
      - ".github/workflows/link-microservice-test.yml"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "src/Services/LinkMicroservice/**"
      - "tests/LinkMicroservice/LinkMicroservice.UnitTests/**"
      - "tests/LinkMicroservice/LinkMicroservice.IntegrationTests/**"
      - ".github/workflows/link-microservice-test.yml"

jobs:
  link-build-unit-testing:
    uses: "./.github/workflows/workflow-build-unit-test.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      test-location: "tests/LinkMicroservice/LinkMicroservice.UnitTests"
      project-name: "LinkMicroservice"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  link-integration-testing:
    uses: "./.github/workflows/workflow-integration-test.yml"
    with:
      test-location: "tests/LinkMicroservice/LinkMicroservice.IntegrationTests"
      project-name: "LinkMicroservice"
    secrets:
      github-token: ${{ secrets.GITHUB_TOKEN }}
  link-analyse:
    uses: "./.github/workflows/workflow-analyse.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      test-location: "tests/LinkMicroservice/LinkMicroservice.UnitTests"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}