name: "link service - build, test & analyse"
on:
  push:
    branches:
      - "main"
      - "development"
      - "feature-**"
    paths:
      - "src/Services/LinkService/**"
      - "tests/LinkService.BTest/**"
      - ".github/workflows/link-service-workflow.yml"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "src/Services/LinkService/**"
      - "tests/LinkService.BTest/**"
      - ".github/workflows/link-service-workflow.yml"

jobs:
  link-testing:
    uses: "./.github/workflows/template-build-test.yml"
    with:
      project-location: "src/Services/LinkService"
      test-location: "tests/LinkService.BTest"
  link-analyse:
    uses: "./.github/workflows/template-analyse.yml"
    with:
      project-location: "src/Services/LinkService"
      test-location: "tests/LinkService.BTest"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}