name: "link service - build, test & analyse"
on:
  push:
    branches:
      - "main"
      - "development"
      - "feature-**"
    paths:
      - "src/Services/LinkMicroservice/**"
      - "tests/LinkMicrosevice/LinkMicroservice.UnitTests/**"
      - ".github/workflows/link-microservice-test.yml"
  pull_request:
    branches:
      - "main"
      - "development"
    paths:
      - "src/Services/LinkMicroservice/**"
      - "tests/LinkMicrosevice/LinkMicroservice.UnitTests/**"
      - ".github/workflows/link-microservice-test.yml"

jobs:
  link-testing:
    uses: "./.github/workflows/template-build-test.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      test-location: "tests/LinkMicrosevice/LinkMicroservice.UnitTests"
      project-name: "LinkMicrosevice"
  link-analyse:
    uses: "./.github/workflows/template-analyse.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      test-location: "tests/LinkMicrosevice/LinkMicroservice.UnitTests"
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}
      github-token: ${{ secrets.GITHUB_TOKEN }}