name: "linkmicroservice - deploy"
on:
  push:
    branches:
      - "release-**"

jobs:
  link-docker-kubernetes:
    uses: "./.github/workflows/template-deploy.yml"
    with:
      project-location: "src/Services/LinkMicroservice"
      project-name: "linkmicroservice"
    secrets:
      docker-username: ${{ secrets.DOCKER_USERNAME }}
      docker-token: ${{ secrets.DOCKER_TOKEN }}
      digitalocean-access-token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      digitalocean-cluster-name: ${{ secrets.DIGITALOCEAN_CLUSTER_NAME }}