name: "build & test template"
on:
  workflow_call:
    inputs:
      project-location:
        required: true
        type: string
        description: "Path to project files"
      test-location:
        required: true
        type: string
        description: "Path to test files"

jobs:
  build-test:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout project code"
        uses: actions/checkout@v2
      
      - name: "Setup dotnet 6"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'
      
      - name: "Restore Nuget dependencies on project"
        run: dotnet restore ${{ inputs.project-location }}

      - name: "Build release version of project"
        run: dotnet build ${{ inputs.project-location }} --no-restore --configuration Release 
      
      - name: "Run test on project"
        run: dotnet test ${{ inputs.test-location }} --logger "trx;LogFileName=test-results.trx" --collect:"XPlat Code Coverage"

      - name: "Create Test Report"
        uses: dorny/test-reporter@v1
        if: success() # run this step even if previous step failed
        with:
          name: "Test results of Unit tests" # Name of the check run which will be created
          path: ${{ inputs.test-location }}/TestResults/test-results.trx # Path to test results
          reporter: dotnet-trx

      - name: "Copy coverage report to convenient location"
        run: cp ${{ inputs.test-location }}/TestResults/**/In/**/coverage.cobertura.xml ${{ inputs.test-location }}/TestResults/coverage.cobertura.xml

      - name: "Create Coverage Summary Report"
        uses: irongut/CodeCoverageSummary@v1.0.2
        with:
          filename: ${{ inputs.test-location }}/TestResults/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'
          thresholds: '55 80'

      - name: "Add Coverage Summary as a PR comment"
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md