name: "Integration test template"
on:
  workflow_call:
    inputs:
      test-location:
        required: true
        type: string
        description: "Path to test files"
      project-name:
        required: true
        type: string
        description: "name of the project"
    secrets:
      github-token:
        required: true

jobs:
  integration-test:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout project code"
        uses: actions/checkout@v2
      
      - name: "Setup dotnet 6"
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '6.0.x'

      - name: "Running helper script for for running Integration tests"
        run: bash ${{ inputs.test-location }}/run-integration-tests.sh ${{ inputs.test-location }}

      - name: "Create Test Report"
        uses: zyborg/dotnet-tests-report@v1
        with:
          project_path: ${{ inputs.test-location }}
          test_results_path: ${{ inputs.test-location }}/TestResults
          report_name: "Test results of Integration tests for ${{ inputs.project-name }}"
          report_title: "Test results of Integration tests for ${{ inputs.project-name }}"
          github_token: ${{ secrets.github-token }}

      - name: "Copy coverage report to convenient location"
        run: cp ${{ inputs.test-location }}/TestResults/**/In/**/coverage.cobertura.xml ${{ inputs.test-location }}/TestResults/coverage.cobertura.xml

      - name: "Create Coverage Summary Report"
        uses: irongut/CodeCoverageSummary@v1.0.2
        with:
          filename: ${{ inputs.test-location }}/TestResults/coverage.cobertura.xml
          badge: true
          format: 'markdown'
          output: 'both'
          thresholds: '55 80'

      - name: "Add Coverage Summary as a PR comment"
        uses: marocchino/sticky-pull-request-comment@v2
        if: github.event_name == 'pull_request'
        with:
          recreate: true
          path: code-coverage-results.md