name: "workflow - security"
on:
  workflow_call:
    inputs:
      project-location:
        required: true
        type: string
        description: "Path to project files"
      project-name:
        required: true
        type: string
        description: "name of the project"
    secrets:
      snyk-token:
        required: true

jobs:
  trufflehog-leaked-credentiaks:
    runs-on: ubuntu-20.04
    steps:
      - name: "checkout project code"
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@v3.4.3
        with:
          path: ./
          base: ${{ github.ref_name }}
          head: HEAD