apiVersion: batch/v1
kind: Job
metadata:
  name: accountmicroservice-dbmigration-job-release-1.0.0
  labels:
    app: accountmicroservice
spec:
  backoffLimit: 1
  template:
    metadata:
      labels:
        app: accountmicroservice
    spec:
      containers:
        - name: accountmicroservice-dbmigration
          image: mrtech12/beavergoose-accountmicroservice-dbmigration:release-1.0.0
          imagePullPolicy: Always
          command: ["dotnet"]
          args: ["AccountMicroservice.DBMigration.dll"]
          env:
            - name: "ConnectionStrings_AccountContext"
              valueFrom:
                secretKeyRef:
                  name: accountmicroservice-dbconnectionstring
                  key: accountcontext
                  optional: false
      restartPolicy: Never
