apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: accountmicroservice-horizontalscaler
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: accountmicroservice-deployment
  minReplicas: 1
  maxReplicas: 3
  targetCPUUtilizationPercentage: 55