apiVersion: apps/v1
kind: Deployment
metadata:
  name: apigateway-deployment
  labels:
    app: apigateway
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apigateway
  template:
    metadata:
      labels:
        app: apigateway
    spec:
      containers:
        - name: apigateway
          image: mrtech12/beavergoose-apigateway:release-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 5001
          env:
            - name: "JWT_Secret"
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: secret
                  optional: false
            - name: "JWT_Issuer"
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: issuer
                  optional: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "320Mi"
              cpu: "256m"