apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: apigateway-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: api.demo-beavergoose.nl
    http:
      paths:
      - pathType: Prefix
        path: "/"
        backend:
          service:
            name: apigateway-service
            port:
              number: 80