apiVersion: apps/v1
kind: Deployment
metadata:
  name: linkmicroservice-deployment
  labels:
    app: linkmicroservice
spec:
  replicas: 2
  selector:
    matchLabels:
      app: linkmicroservice
  template:
    metadata:
      labels:
        app: linkmicroservice
    spec:
      serviceAccountName: dbmigration-account
      initContainers:
        - name: "linkmicroservice-dbmigration-init"
          image: "groundnuty/k8s-wait-for:1.3"
          imagePullPolicy: Always
          args:
            - "job"
            - "linkmicroservice-dbmigration-job-release-1.0.0"
      containers:
        - name: linkmicroservice
          image: mrtech12/beavergoose-linkmicroservice:release-1.0.0
          imagePullPolicy: Always
          ports:
            - containerPort: 7000
          env:
            - name: "ConnectionStrings_LinkContext"
              valueFrom:
                secretKeyRef:
                  name: linkmicroservice-dbconnectionstring
                  key: linkcontext
                  optional: false
            - name: "RabbitMQ_HostName"
              value: "rabbitmq-service"
            - name: "RabbitMQ_Port"
              value: "5672"
            - name: "JWT_Secret"
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: secret
                  optional: false
            - name: "JWT_Issuer"
              valueFrom:
                secretKeyRef:
                  name: jwt-config
                  key: issuer
                  optional: false
            - name: "Seq_ServerUrl"
              value: "my-seq.default.svc.cluster.local"
            - name: "Seq_ApiKey"
              valueFrom:
                secretKeyRef:
                  name: seq-apikeys
                  key: linkmicroservice
                  optional: false
          resources:
            requests:
              memory: "128Mi"
              cpu: "128m"
            limits:
              memory: "512Mi"
              cpu: "256m"
